spring:
    # mysql
    datasource:
        url: jdbc:mysql://192.168.102.17:3306/insurance?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: WWW.RokyInfo.Com
        driverClassName: com.mysql.jdbc.Driver