spring:
    # mysql
    datasource:
        url: jdbc:mysql://localhost:3306/insurance?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: caoyy
        driverClassName: com.mysql.jdbc.Driver

    #AMQP
    rabbitmq:
        host: 192.168.102.17
        port: 5672
        username: guest
        password: guest

business:
    insurance:
      image:
        storage:
          address: /Users/caoyangyang/insurance-pic/
        request:
          url:
            prefix: http://localhost/insurance/res/

remote:
    url: http://192.168.102.17:19606