# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8099

# spring
spring:
    application:
      name: insurance

    profiles:
      active: dev

    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

# Mybatis
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

business:
    insurance:
      image:
        storage:
          address: /Users/caoyangyang/insurance-pic/
        request:
          url:
            prefix: http://localhost/insurance/res/

remote:
    url: http://192.168.102.17:19606

