spring:
    # mysql
    datasource:
        url: jdbc:mysql://localhost:3306/insurance?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: caoyy
        driverClassName: com.mysql.jdbc.Driver